---
title: "metacrawlr"
format: 
  gfm:
    df_print: kable
---



```r
if(!require(devtools)){install.packages("devtools")}
devtools::install_github("marbotte/metacrawlr")
```


```{r}
library(metacrawlr)
```


## Metadata extraction from the datadir of an IPT instance

Here, as an example, I downloaded the datadir of an IPT instance on my computer:

```{r}
DATADIR<-"/home/marius_gt/Travail/Data/IPTs/permisos-3.1.5/resources/"
```

First we list the files and their encodings/languages (this takes a lot of time, if you are confident in knowing the encodings, I suggest using the encoding argument instead).

```{r}
filesPermi<-ipt_listFiles(DATADIR)
knitr::kable(head(filesPermi))
```

```{r , warning=F}
extractedXml<-ipt_extractXml(filesPermi, modeExtract ="both" )
```


```{r}
metaList_permi<-metaListFromXml(extractedXml)
```

```{r}
structPermi<-extractStructureListDocuments(metaList_permi)
gnv_permi<-groupsAndVariables(structPermi)
tabs_permi<-extractTables(metaList_permi,structPermi,gpsAndVar = gnv_permi)
```


```{r}
xlFile_permi<-"../data_metadatos_catalogos/exportPermi.xlsx"
sqlite_permi<-"../data_metadatos_catalogos/permi.sqlite"
tabs_permi<-sqlize_extractedTables(tabs_permi)
exportXL(tabs_permi,file=xlFile_permi)
dbpermi<-exportSQLite(tabs_permi,sqlite_file = sqlite_permi)
```


## Ejemplo Ceiba

```{r}
DATADIR <- "/home/marius_gt/Travail/Data/IPTs/Ceiba/resources/"
```

```{r}
filesCeiba<-ipt_listFiles(DATADIR)
knitr::kable(head(filesCeiba))
```

```{r , warning=F}
extractedXml<-ipt_extractXml(filesCeiba, modeExtract ="both" )
```


```{r}
metaList_ceiba<-metaListFromXml(extractedXml)
```

```{r}
structCeiba<-extractStructureListDocuments(metaList_ceiba)
gnv_ceiba<-groupsAndVariables(structCeiba)
tabs_ceiba<-extractTables(metaList_ceiba,structCeiba,gpsAndVar = gnv_ceiba)
tabs_ceiba_sql<-sqlize_extractedTables(tabs_ceiba)
```

```{r}
library(RPostgres)
mI2D<-dbConnect(drv=Postgres(),dbname="meta_i2d")
schemaCeiba<-"ceiba"
exportPostgres(tabs_ceiba_sql,mI2D,schema=schemaCeiba,overwrite = T,createFKindices = T)
```

